name: external_textures
description: A test of Flutter integrating external textures.

environment:
  sdk: ^3.11.0-0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  image: ^4.3.0


flutter:
  uses-material-design: true
  assets:
    - assets/small.mp4

# PUBSPEC CHECKSUM: muq7bk
