// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import '../base/file_system.dart';
import '../plugins.dart';
import '../project.dart';

/// Dynamically discovers legacy Gradle plugins and registers them as Bazel
/// dependencies within the primary Android workspace.
class NativePluginRegistrant {
  NativePluginRegistrant({required FileSystem fileSystem}) : _fileSystem = fileSystem;

  final FileSystem _fileSystem;

  /// Generates the `plugins.bzl` file bridging plugin dependencies into Bazel.
  Future<void> generatePluginsBzl(FlutterProject project, List<Plugin> plugins) async {
    final File pluginsBzlFile = project.android.hostAppGradleRoot.childFile('plugins.bzl');

    final workspaces = StringBuffer();
    final deps = StringBuffer();

    workspaces.writeln('def flutter_plugin_workspaces():');
    deps.writeln('flutter_plugin_deps = [');

    var hasNativePlugins = false;

    for (final plugin in plugins) {
      final Directory pluginAndroidDir = _fileSystem
          .directory(plugin.path)
          .childDirectory('android');
      if (!pluginAndroidDir.existsSync()) {
        continue;
      }

      hasNativePlugins = true;

      workspaces.writeln('    native.local_repository(');
      workspaces.writeln('        name = "plugin_${plugin.name}",');
      workspaces.writeln('        path = "${plugin.path}",');
      workspaces.writeln('    )');

      deps.writeln('    "@plugin_${plugin.name}//android:plugin_${plugin.name}_aar",');
    }

    if (!hasNativePlugins) {
      workspaces.writeln('    pass');
    }

    deps.writeln(']');

    final content =
        '''
# GENERATED FILE - DO NOT EDIT.
# This file is generated by flutter_tools to map legacy Gradle plugins into the Bazel dependency tree.

$workspaces

$deps
''';

    pluginsBzlFile.writeAsStringSync(content);
  }
}
