# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("mutators_stack") {
  sources = [
    "../android_mutators_stack.h",
  ]

  public_configs = [ "//flutter:config" ]

  public_deps = [
    "//flutter/display_list",
    "//flutter/fml",
  ]
}
